project:
  type: website
  output-dir: docs

website:
  title: Hannah Kalvin
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: pages/publications.qmd
        text: Publications
      - href: pages/cv_resume1.qmd
        text: Resume


format:
  html:
    theme: [minty, styles/custom.scss]
    css: styles/styles.css
    toc: false

editor: source
