---
title: Resume
format:
  html:
    toc: true
  pdf:
    colorlinks: false
    mainfont: Arial
    fontsize: 11pt
    include-in-header:
      text: |
        \usepackage[lmargin = 0.7in,rmargin = 0.7in,
        tmargin =0.9in, bmargin = 0.9in]{geometry}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        
        \fancyhf{}
        \rhead{\thepage}
        \lhead{Hannah Kalvin, MSPH}
        
        \makeatletter         
        \renewcommand\maketitle{
        \begin{center}
        {\Large \textbf{Hannah Kalvin, MSPH}}\\
        \vspace{1mm}
        \normalsize hannahlkalvin@gmail.com\\
        \vspace{1mm}
        Updated July 2026
        \end{center}} 
        \makeatother
     
        \addtokomafont{disposition}{\rmfamily}
format-links: [pdf]
---

## EDUCATION

**Master of Science in Public Health in Biostatistics**

*Emory University, Atlanta, Georgia* [*Aug 2019 --- May 2021*]{.cvdate}

-   Relevant Coursework: Survival Analysis Methods, Modern Regression Analysis, Clinical Trials Methodology, Biostatistical Methods, Probability Theory, Applied Linear Models, Statistical Inference, Machine Learning, Statistical Practice, Epidemiology Methods

-   Masters Capstone: "Assessing the Relationship between Breast Cancer Mortality and BMI by State and Race" (Advisor: Jeffrey Switchenko, PhD)


**Bachelor of Science in Public Health, Minor in Biological Sciences (magna cum laude)**

*The George Washington University, Washington, DC* [*Aug 2012 --- May 2016*]{.cvdate}

## PROFESSIONAL EXPERIENCE

### Memorial Sloan Kettering Cancer Center

**Research Biostatistician II** [*Feb 2025 --- Present*]{.cvdate}

**Research Biostatistician I** [*Sep 2022 --- Feb 2025*]{.cvdate}

**Assistant Research Biostatistician** [*Jul 2021 --- Sep 2022*]{.cvdate}

-   Collaborate with clinicians and researchers from design to publication phase to answer questions relating to cancer genomics, survival outcomes, etc. using statistical analyses and visualizations
-   Perform statistical analysis in SAS and R for Global Cancer Disparities Initiative, Hepato-Pancreatic-Biliary Surgery, and Melanoma groups

### Emory Rollins School of Public Health

**Graduate Research Assistant** [*May 2020 --- May 2021*]{.cvdate}

-   Researched state/region and race-specific obesity patterns in relation to breast cancer mortality over time
-   Compiled and analyze SEER and BRFSS data from 1990-2017 using SAS, SAS-callable SUDAAN, and R
-   Produced tables, figures, and maps summarizing obesity and breast cancer mortality rates by state and race
-   Analyzed relationship between breast cancer mortality count and BMI by state and race using Poisson Regression

### Emory Biostatistics Collaboration Core

**Data Analyst** [*June 2020 --- August 2020*]{.cvdate}

-   Cleaned Michigan Polybrominated Biphenyls (PBB) Cohort datasets using SAS in order to make data available via a new data management platform
-   Created data dictionaries for Michigan PBB Cohort datasets with consistent search term/field label coding
-   Conducted power and sample size analyses for NIH grants
-   Performed quality assurance checks on psychometric datasets

### Emory Rollins School of Public Health

**BIOS 500 Graduate Teaching Assistant** [*Aug 2020 --- Dec 2020*]{.cvdate}

-   Created answer keys and graded assignments and exams for 105 students
-   Assisted 105 students in learning SAS programming and statistical methods

### Centers for Disease Control and Prevention

**Epidemiology/Data Management Graduate Assistant** [*Nov 2019 --- May 2020*]{.cvdate}

-   Analyzed 400,000 observation dataset (National Tuberculosis Surveillance System) and produced SAS summaries
-   Composed original research proposal for analytic project based on National Tuberculosis Surveillance System

### WCG Statistics Collaborative (formerly Statistics Collaborative, Inc)

**Senior Research Associate** [*Jul 2018 --- Jul 2019*]{.cvdate}

**Research Associate** [*Jun 2017 --- Jul 2018*]{.cvdate}

**Research Assistant** [*Jun 2016 --- Jun 2017*]{.cvdate}

-   Coordinated and supported several Phase 2 and Phase 3 clinical trials with indications for: heart failure, cardiovascular disease, chronic kidney disease, pediatric growth hormone treatment, and HIV
-   Managed and led multiple projects under supervision of Statistical Scientists for: orphan neurological disorders, infectious disease, and cardiovascular disease in a genetically pre-specified population
-   Wrote and reviewed data monitoring committee reports
-   Prepared table, figure, and listing shells for statistical analysis plans
-   Utilized standard SAS code and in-house macros to produce and audit graphs, tables, and listings
-   Created and audited SAS analysis programs

## SKILLS

Expert: R, RStudio, SAS, Quarto, Git/GitHub, Microsoft Office Suite

Proficient: Python, Joinpoint Regression, SAS-callable SUDAAN, SEER*Stat

Familiar: Docker, GIS, LaTeX

## CERTIFICATION

SAS Certified Specialist: Base Programming Using SAS 9.4  [*Issued December 2019*]{.cvdate}



## PUBLICATIONS

::: {.content-hidden when-format="pdf"}
For the most up to date list of publications, check out my [Google Scholar](https://scholar.google.com/citations?user=Gat1Du8AAAAJ&hl=en) page.
:::

```{r}
#| echo: false
#| message: false
#| warning: false
#| results: asis



library(tidyverse)
df_articles <- 
  scholar::get_publications('Gat1Du8AAAAJ') %>%
  as_tibble() %>%
  # delete abstracts
  filter(
    !is.na(year), # missing publication year
    title != str_to_upper(title), # title is all upper case
    !str_detect(number, fixed("Supplement")), # number contains 'Supplement'
    !str_detect(number, fixed("_suppl")), # number contains '_suppl'
    !str_detect(number, fixed("SUPPL")),
    !str_detect(title, fixed("preprint")),
    !str_detect(stringr::str_to_lower(title), fixed("abstract")),
    !str_detect(stringr::str_to_upper(title),fixed("YIA26-003:")),
    !str_detect(stringr::str_to_lower(title),fixed("sa1915 ")),
    !str_detect(stringr::str_to_lower(title),fixed("96p ")),
    !str_detect(stringr::str_to_lower(title),fixed("1102p ")),
    !str_detect(stringr::str_to_lower(title),fixed("(vol 28, pg 978, 2023)")),
    !str_detect(stringr::str_to_lower(title),fixed("management and outcomes of patients with recurrence of cutaneous melanoma during or after completion of adjuvant immunotherapy: a multicenter study")),
    !str_detect(stringr::str_to_lower(title),fixed("local recurrence following management of primary merkel cell carcinoma")),
    !str_detect(stringr::str_to_lower(title),fixed("has management of locally advanced intrahepatic cholangiocarcinoma evolved with the evidence? trends and practice patterns from the national cancer database")),
    !str_detect(stringr::str_to_lower(title),fixed("development of a translational tumoroid-organoid platform revealing tumor-specific radiosensitization in rectal cancer using matched patient-derived models")),
    !str_detect(stringr::str_to_lower(journal),fixed("hpb")),
    !str_detect(stringr::str_to_lower(title),fixed("evaluation of the implementation of enhanced recovery after surgery pathways in pancreatic surgery")),
    !str_detect(stringr::str_to_lower(title),fixed("hepatic artery infusion pump placement technical complication and salvage rate")) ## will need to fix this once manuscript is published 
  ) 

df_articles <- df_articles %>%
  # clean up authors
  mutate(
    journal=case_when(
      journal=="" & title=="A phase II study of N-acetylcysteine in cancer patients with severe COVID-19: clinical outcomes and biological correlates" ~ "medRxiv",
      journal=="ONCOLOGIST" ~ "The Oncologist",
      journal!="medRxiv" & !stringr::str_detect(journal,"JCO") & 
        !stringr::str_detect(journal,"HPB") & 
        !stringr::str_detect(journal,"JAMA")~ stringr::str_to_title(journal),
      stringr::str_detect(journal,"JAMA oncology")==TRUE ~ "JAMA Oncology",
      TRUE ~ journal
    )
  ) %>% 
  filter(journal!="") %>% 
  distinct(title,.keep_all=TRUE) %>% 
  mutate(
    author = str_replace(author, fixed("..."), fixed("and others")),
    author = 
      case_when(
        str_detect(author, fixed("HL Kalvin")) ~ 
          str_replace(author, fixed("HL Kalvin"), fixed("**HL Kalvin**")),
        str_detect(author, fixed("H Kalvin")) ~ 
          str_replace(author, fixed("H Kalvin"), fixed("**H Kalvin**")),
        !str_detect(author, fixed("Kalvin")) ~
          str_replace(author, fixed("and others"), fixed("**HL Kalvin**, and others")),
        TRUE ~ author
      ),
    citation = 
      str_glue('{author} ({year}). "{title}." *{journal}, {number}*') %>%
      as.character()
  ) %>%
  arrange(desc(year)) %>%
  mutate(order = 1:nrow(.)) %>%
  arrange(order)


# df_articles %>%
#   pull(citation) %>% 
#   paste(collapse = "<br><br>") %>%
#   cat()

df_articles %>%
  pull(citation) %>% 
  paste(collapse = "<br><br></li><li>") %>% 
  paste0("<ol><li>", ., "</ol>") %>%
  cat()

```

## PRESENTATIONS AND POSTERS

### Presentations

| **Expanding biostatistics research and training efforts beyond MSK - A global health initiative**
| Seminar for Memorial Sloan Kettering Department of Epidemiology and Biostatistics, New York, NY, November 2025

| **Linear Regression II: Regression Diagnostics**
| Lecture for Obafemi Awolowo University (Ile Ife, Nigeria), Virtual, May 2024

| **Linear Regression I: Introduction and Assumptions**
| Lecture for Obafemi Awolowo University (Ile Ife, Nigeria), Virtual, May 2024

### Poster

| **Real-world evidence following a clinical trial: An application in biliary tract cancer**
| Society for Clinical Trials Annual Meeting, Boston, MA, May 2024

## PROFESSIONAL SERVICE

**Society for Clinical Trials**

*Program Committee Member* [*2025 --- present*]{.cvdate}

-   Review and select applications for sessions at annual meeting
-   Ensure sessions represent diverse interests
-   Choose poster award recipients

*Member* [*2023 --- present*]{.cvdate}

**Memorial Sloan Kettering Bridge to Biostats**

*Member* [*2021 --- present*]{.cvdate}

-   Co-lead 8th grade and high school “Biostats Days” to introduce students to biostatistics
-   Mentor high school students part of the Bridge to Biostats Summer Program (B2BSP)
-   Teach introduction to R Studio for high school students in B2BSP

**Peer Reviewer**

Cell Reports Medicine

Nature Communications

## COMMUNITY SERVICE

**Cycle for Survival**

*Team Captain* [*2025 --- 2026*]{.cvdate}

| Lead fundraising efforts for department team (Team Bell Curve)

*Team member* [*2021 --- 2025*]{.cvdate}

::: {.content-hidden when-format="html"}
## References

Available upon request
:::
